name: Build, package and release clang+llvm
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        arch: [x86-64, arm64]
        os: [macos-15-intel, macos-15]
        exclude:
          - os: macos-15-intel
            arch: arm64
          - os: macos-15
            arch: x86-64
      fail-fast: true
      max-parallel: 2
    uses: ./.github/workflows/jobs.yml
    with:
      arch: ${{ matrix.arch }}
      os:  ${{ matrix.os }}
